version: '3.9'

services: 
    
    #mysql Server
    db:
        image: mysql
        container_name: db
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_DATABASE: aplicacao
            MYSQL_ROOT_PASSWORD: root
        networks: 
            - app-network

    #nginx service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports: 
            - "80:80"
        networks: 
            - app-network

#docker network
networks: 
    app-network:
        driver: bridge
